# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
development:
  adapter: postgresql
  encoding: unicode
  database: drivewave_dev
  pool: 5
  username: drivewave
  password: drivewave
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: drivewave_test
  pool: 5
  username: drivewave
  password: drivewave
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: drivewave_pro
  pool: 5
  username: drivewave
  password: drivewave
  host: localhost
  port: 5432
