require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotivationsController do

  def mock_motivation(stubs={})
    @mock_motivation ||= mock_model(Motivation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all motivations as @motivations" do
      Motivation.stub(:all) { [mock_motivation] }
      get :index
      assigns(:motivations).should eq([mock_motivation])
    end
  end

  describe "GET show" do
    it "assigns the requested motivation as @motivation" do
      Motivation.stub(:find).with("37") { mock_motivation }
      get :show, :id => "37"
      assigns(:motivation).should be(mock_motivation)
    end
  end

  describe "GET new" do
    it "assigns a new motivation as @motivation" do
      Motivation.stub(:new) { mock_motivation }
      get :new
      assigns(:motivation).should be(mock_motivation)
    end
  end

  describe "GET edit" do
    it "assigns the requested motivation as @motivation" do
      Motivation.stub(:find).with("37") { mock_motivation }
      get :edit, :id => "37"
      assigns(:motivation).should be(mock_motivation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created motivation as @motivation" do
        Motivation.stub(:new).with({'these' => 'params'}) { mock_motivation(:save => true) }
        post :create, :motivation => {'these' => 'params'}
        assigns(:motivation).should be(mock_motivation)
      end

      it "redirects to the created motivation" do
        Motivation.stub(:new) { mock_motivation(:save => true) }
        post :create, :motivation => {}
        response.should redirect_to(motivation_url(mock_motivation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved motivation as @motivation" do
        Motivation.stub(:new).with({'these' => 'params'}) { mock_motivation(:save => false) }
        post :create, :motivation => {'these' => 'params'}
        assigns(:motivation).should be(mock_motivation)
      end

      it "re-renders the 'new' template" do
        Motivation.stub(:new) { mock_motivation(:save => false) }
        post :create, :motivation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested motivation" do
        Motivation.stub(:find).with("37") { mock_motivation }
        mock_motivation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :motivation => {'these' => 'params'}
      end

      it "assigns the requested motivation as @motivation" do
        Motivation.stub(:find) { mock_motivation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:motivation).should be(mock_motivation)
      end

      it "redirects to the motivation" do
        Motivation.stub(:find) { mock_motivation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(motivation_url(mock_motivation))
      end
    end

    describe "with invalid params" do
      it "assigns the motivation as @motivation" do
        Motivation.stub(:find) { mock_motivation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:motivation).should be(mock_motivation)
      end

      it "re-renders the 'edit' template" do
        Motivation.stub(:find) { mock_motivation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested motivation" do
      Motivation.stub(:find).with("37") { mock_motivation }
      mock_motivation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the motivations list" do
      Motivation.stub(:find) { mock_motivation }
      delete :destroy, :id => "1"
      response.should redirect_to(motivations_url)
    end
  end

end
