require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ThemesController do

  def mock_theme(stubs={})
    @mock_theme ||= mock_model(Theme, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all themes as @themes" do
      Theme.stub(:all) { [mock_theme] }
      get :index
      assigns(:themes).should eq([mock_theme])
    end
  end

  describe "GET show" do
    it "assigns the requested theme as @theme" do
      Theme.stub(:find).with("37") { mock_theme }
      get :show, :id => "37"
      assigns(:theme).should be(mock_theme)
    end
  end

  describe "GET new" do
    it "assigns a new theme as @theme" do
      Theme.stub(:new) { mock_theme }
      get :new
      assigns(:theme).should be(mock_theme)
    end
  end

  describe "GET edit" do
    it "assigns the requested theme as @theme" do
      Theme.stub(:find).with("37") { mock_theme }
      get :edit, :id => "37"
      assigns(:theme).should be(mock_theme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created theme as @theme" do
        Theme.stub(:new).with({'these' => 'params'}) { mock_theme(:save => true) }
        post :create, :theme => {'these' => 'params'}
        assigns(:theme).should be(mock_theme)
      end

      it "redirects to the created theme" do
        Theme.stub(:new) { mock_theme(:save => true) }
        post :create, :theme => {}
        response.should redirect_to(theme_url(mock_theme))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved theme as @theme" do
        Theme.stub(:new).with({'these' => 'params'}) { mock_theme(:save => false) }
        post :create, :theme => {'these' => 'params'}
        assigns(:theme).should be(mock_theme)
      end

      it "re-renders the 'new' template" do
        Theme.stub(:new) { mock_theme(:save => false) }
        post :create, :theme => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested theme" do
        Theme.stub(:find).with("37") { mock_theme }
        mock_theme.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :theme => {'these' => 'params'}
      end

      it "assigns the requested theme as @theme" do
        Theme.stub(:find) { mock_theme(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:theme).should be(mock_theme)
      end

      it "redirects to the theme" do
        Theme.stub(:find) { mock_theme(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(theme_url(mock_theme))
      end
    end

    describe "with invalid params" do
      it "assigns the theme as @theme" do
        Theme.stub(:find) { mock_theme(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:theme).should be(mock_theme)
      end

      it "re-renders the 'edit' template" do
        Theme.stub(:find) { mock_theme(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested theme" do
      Theme.stub(:find).with("37") { mock_theme }
      mock_theme.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the themes list" do
      Theme.stub(:find) { mock_theme }
      delete :destroy, :id => "1"
      response.should redirect_to(themes_url)
    end
  end

end
